"""
CIRCOR Lakehouse Pipeline - Step 04: IFS Cloud Automated Hold Remediation Daemon
Polls the Gold Lakehouse remediation queue or IFS OData endpoint.
When an operation breaches COS variance (>15%) or scrap limits (>0),
issues an administrative ParkOrder action back to IFS Cloud to quarantine WIP.
"""

import os
import sys
import json
import time
import requests
from typing import List, Dict, Any

class CircorRemediationDaemon:
    def __init__(self, api_base_url: str = "http://localhost:8000/ifs", gold_dir: str = "data/gold"):
        self.api_base_url = api_base_url
        self.gold_dir = gold_dir
        self.park_action_url = f"{api_base_url}/ShopOrderHandling.svc/ShopOrderSet('{{order_no}}')/ParkOrder"

    def execute_hold_from_queue(self) -> List[Dict[str, Any]]:
        """Reads remediation_hold_queue.json generated by Gold layer and posts ParkOrder."""
        queue_path = os.path.join(self.gold_dir, "remediation_hold_queue.json")
        actions_taken = []

        if not os.path.exists(queue_path):
            print(f"[REMEDIATION DAEMON] No queue file found at {queue_path}. Polling IFS directly.")
            return self.scan_and_park_live_orders()

        with open(queue_path, "r", encoding="utf-8") as f:
            candidates = json.load(f)

        for item in candidates:
            order_no = item.get("order_no")
            reason = (
                f"COS Lean Breach: Variance {item.get('variance_percentage')}% | "
                f"Scrap {item.get('qty_scrapped')} units on Heat Lot {item.get('heat_lot_no')}"
            )
            action_result = self.issue_park_order(order_no, reason)
            actions_taken.append(action_result)

        return actions_taken

    def scan_and_park_live_orders(self) -> List[Dict[str, Any]]:
        """Scans live IFS Shop Orders, checks variance and scrap, and triggers holds."""
        orders_url = f"{self.api_base_url}/ShopOrderHandling.svc/ShopOrderSet"
        actions_taken = []

        try:
            res = requests.get(orders_url, timeout=5)
            if res.status_code != 200:
                print(f"[REMEDIATION DAEMON] Could not connect to IFS at {orders_url}")
                return actions_taken
            orders = res.json()
        except Exception as e:
            print(f"[REMEDIATION DAEMON] Network error connecting to IFS: {e}")
            return actions_taken

        for op in orders:
            order_no = op.get("order_no")
            qty_scrapped = float(op.get("qty_scrapped", 0.0))
            planned_cost = (op.get("planned_labor_hours", 0) * op.get("standard_labor_rate", 0)) + \
                           (op.get("planned_machine_hours", 0) * op.get("standard_machine_rate", 0))
            actual_cost = (op.get("actual_labor_hours", 0) * op.get("standard_labor_rate", 0)) + \
                          (op.get("actual_machine_hours", 0) * op.get("standard_machine_rate", 0))
            
            variance_pct = ((actual_cost - planned_cost) / planned_cost * 100) if planned_cost > 0 else 0

            if (qty_scrapped > 0 or variance_pct > 15.0) and op.get("rowstate") != "Parked":
                reason = f"Automated COS Hold: Variance {variance_pct:.1f}%, Scrap: {qty_scrapped} on Heat Lot {op.get('heat_lot_no')}"
                result = self.issue_park_order(order_no, reason)
                actions_taken.append(result)

        return actions_taken

    def issue_park_order(self, order_no: str, reason: str) -> Dict[str, Any]:
        """Invokes IFS Cloud OData Action to park the shop order."""
        target_url = self.park_action_url.format(order_no=order_no)
        payload = {"order_no": order_no, "reason": reason}

        try:
            res = requests.post(target_url, json=payload, timeout=5)
            if res.status_code == 200:
                print(f"[SUCCESS] Placed IFS Administrative Hold on Shop Order {order_no}: {reason}")
                return {"order_no": order_no, "status": "Parked", "response": res.json()}
            else:
                print(f"[ERROR] Failed to park order {order_no}: HTTP {res.status_code} - {res.text}")
                return {"order_no": order_no, "status": "Failed", "error": res.text}
        except Exception as e:
            print(f"[EXCEPTION] Park request failed for order {order_no}: {e}")
            return {"order_no": order_no, "status": "Exception", "error": str(e)}

if __name__ == "__main__":
    endpoint = os.environ.get("IFS_ENDPOINT", "http://localhost:8000/ifs")
    daemon = CircorRemediationDaemon(api_base_url=endpoint)
    daemon.execute_hold_from_queue()
